from src.bot.keyboards.inline.menu import (
    back_menu,
    deep_scan_mp,
    deep_scan_own_setup,
    express_setup,
    infographic_photo_setup,
    infographic_variants,
    main_menu,
    reviews_result_keyboard,
    reviews_rival_setup,
    reviews_selection,
    reviews_tone,
    seo_keywords_setup,
    seo_mp,
    seo_result_keyboard,
    submenu,
)

__all__ = [
    "back_menu",
    "deep_scan_mp",
    "deep_scan_own_setup",
    "express_setup",
    "infographic_photo_setup",
    "infographic_variants",
    "main_menu",
    "reviews_result_keyboard",
    "reviews_rival_setup",
    "reviews_selection",
    "reviews_tone",
    "seo_keywords_setup",
    "seo_mp",
    "seo_result_keyboard",
    "submenu",
]
